### ISSUE TITLE
Issue while counting/exploring files and downloading data

### ISSUE THREAD

**Issue by guiattard** [ISI-MIP/isimip-client#5]
While testing the ismip-client capabilities, two issues have been identified:
- the first issue relies on the discrepancies of files count between the isimip-client and the isimip repository, and the wrong behavior of of the `client.files` function when using the `tree` argument,
- the second issue relies on the impossibility to select and download some filespaths around alocation of interest.

Both issues are described in the [Colab notebook attached](https://colab.research.google.com/drive/1WEory4_nLCFpXB2tmoHsMT9tgHhXXIap?usp=sharing).

**Comment by jochenklar** [comment]
Hi @guiattard , sorry that it took so long. I had a look at your very detailed notebook (thanks for the effort!).

The first problem arises because you use the `client.files()` method and not `client.datasets`. For daily data, we split the data along decades and combine the files to datasets when publishing them on the repository. e.g. https://data.isimip.org/datasets/44b6e025-6b69-49f5-82f5-21f807b413f4/. For your selection there are 26398 files in 10415 datasets. Maybe we need to be more clear about this in our documentation.

I think you ran into the second problem because, the API was used by other users. I tried it now from a local script and it worked in less than a minute. It could also be a problem with Google Colab so please try again.

**Comment by guiattard** [comment]
> For your selection there are 26398 files in 10415 datasets. Maybe we need to be more clear about this in our documentation.

Yes, this is what the client returns. But it dismatches the number of files indicated in the filelist.txt downloaded on the [isimip repository with same specifiers](https://data.isimip.org/search/tree/ISIMIP3b/OutputData/water_global/). My `filelist.txt` has 21709 lines which is not consistant with the isimip-client info.

Regading my issue #2, I agree, it seems to work today. With the same script. So I cannot reproduce the bug.

**Comment by jochenklar** [comment]
Yes, you are right, there was a `distinct` clause missing for the files api (https://github.com/ISI-MIP/isimip-data/commit/b6d43fd0556e5680e9fa3e99840acd567c783648) so the datasets which are linked from different sectors appear multiple times (in this case CLASSIC).

Also for files API the tree filter was missing completely (https://github.com/ISI-MIP/isimip-data/commit/90da1ff8590cc7fb2d1d7295af877a2aec3a343a).

The changes are already live.
